### ISSUE TITLE
[BUG] segfault in mcpe_viz::ParsedVillageInfo::set_dwellers with NULL tag

### ISSUE THREAD

**Issue by stsquad** [bedrock-viz/bedrock-viz#136]
**Describe the bug**

On some of my worlds bedrock_viz segfaults due to attempting to cast a NULL pointer. 

**To Reproduce**

Short of sending you my world you'll have to make do with this backtrace:

```
[   info]   Processing records: 270000 / 279470 (96.6%)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7d81def in __dynamic_cast () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7d81def in __dynamic_cast () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000555555615a2d in nbt::tag::as<nbt::tag_list> (this=0x0) at /home/alex/src/bedrock-viz.git/third_party/libnbtplusplus/include/tag.h:147
#2  0x00005555556161b4 in nbt::value::as<nbt::tag_list> (this=0x55555a21aeb0) at /home/alex/src/bedrock-viz.git/third_party/libnbtplusplus/include/value.h:210
#3  0x0000555555611282 in mcpe_viz::ParsedVillageInfo::set_dwellers (this=0x55555588a400, tc=...) at /home/alex/src/bedrock-viz.git/src/nbt.cc:2561
#4  0x00005555556035e4 in mcpe_viz::parseNbt_village (info_tags=std::vector of length 1, capacity 1 = {...}, player_tags=std::vector of length 1, capacity 1 = {...}, dweller_tags=std::vector of length 1, capacity 1 = {...}, poi_tags=std::vector of length 1, capacity 1 = {...}, playerMap=std::map with 6 elements = {...}) at /home/alex/src/bedrock-viz.git/src/nbt.cc:2927
#5  0x00005555555ddfb6 in mcpe_viz::MinecraftWorld_LevelDB::dbParse (this=0x55555583b1c0) at /home/alex/src/bedrock-viz.git/src/world/world.cc:843
#6  0x0000555555576fa7 in main (argc=6, argv=0x7fffffffe3c8) at /home/alex/src/bedrock-viz.git/src/main.cc:931
(gdb) f 1
#1  0x0000555555615a2d in nbt::tag::as<nbt::tag_list> (this=0x0) at /home/alex/src/bedrock-viz.git/third_party/libnbtplusplus/include/tag.h:147
147         return dynamic_cast<T&>(*this);
(gdb) p this
$1 = (nbt::tag * const) 0x0
(gdb) frame 2
#2  0x00005555556161b4 in nbt::value::as<nbt::tag_list> (this=0x55555a21aeb0) at /home/alex/src/bedrock-viz.git/third_party/libnbtplusplus/include/value.h:210
210         return tag_->as<T>();
(gdb) p tag_
$2 = std::unique_ptr<nbt::tag> = {get() = 0x0}
(gdb) frame 3
#3  0x0000555555611282 in mcpe_viz::ParsedVillageInfo::set_dwellers (this=0x55555588a400, tc=...) at /home/alex/src/bedrock-viz.git/src/nbt.cc:2561
2561                                nbt::tag_list pos = dc["last_saved_pos"].as<nbt::tag_list>();
(gdb) p dc["last_saved_pos"]
Invalid cast.
(gdb) p this
$3 = (mcpe_viz::ParsedVillageInfo * const) 0x55555588a400
(gdb) p *$
$4 = {pos = {x = 2288, y = 66, z = 194, valid = true}, x0 = 2256, x1 = 2320, y0 = 54, y1 = 78, z0 = 162, z1 = 226, players = std::map with 0 elements, villagers = std::vector of length 0, capacity 0, golems = std::vector of length 0, capacity 0, d2 = std::vector of length 0, capacity 0, cats = std::vector of length 0, capacity 0}
(gdb) p it
$5 = (const nbt::value &) @0x555557a68b80: {tag_ = std::unique_ptr<nbt::tag> = {get() = 0x55555a264160}}
(gdb) p dc
$6 = {<nbt::detail::crtp_tag<nbt::tag_compound>> = {<nbt::tag> = {_vptr.tag = 0x555555815f30 <vtable for nbt::tag_compound+16>}, <No data fields>}, static type = nbt::tag_type::Compound, tags = std::map with 3 elements = {["ID"] = {tag_ = std::unique_ptr<nbt::tag> = {get() = 0x5555596822c0}}, ["TS"] = {tag_ = std::unique_ptr<nbt::tag> = {get() = 0x555556ad0000}}, ["last_saved_pos"] = {tag_ = std::unique_ptr<nbt::tag> = {get() = 0x0}}}}
```

**Expected behavior**

Don't segfault when processing missing data.

**Environment Information:**
 - OS: Linux
 - bedrock-viz version: current master
 - Build toolchain information (if applicable):  c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Additional context**
I suspect the x86 Android build of Minecraft is capable of corrupting Bedrock servers state leading to null tags you wouldn't ordinarily see.

**Comment by Desterly** [comment]
There was another recent commit to fix an issue with villages and this one looks very similar in nature.

The current code assumes all tags / references exist and as we've noticed with a few of the recent versions of MC, not all tags are written to the worlds.  Based off the stack trace that appears to be the issue here as well.

If you are comfortable, I can create a PR to test with, otherwise if it's possible to share the world I can test directly.

**Comment by stsquad** [comment]
I'm happy to test PRs and give feedback. I'm afraid my C++ is rusty so I'll leave it to others more fluent to write the code ;-)

**Comment by Desterly** [comment]
@stsquad - if you want to build with PR #137 and let us know if that fixes the crash that would be great.
